baseURL = 'https://totalintegrity.eu/'
locale = 'en-us'
title = 'Total Integrity'
theme = "papermod"

[outputs]
  home = ["HTML", "RSS", "JSON"]

[params]
  searchEnabled = true
  fuseOpts = { isCaseSensitive = false, includeScore = true, shouldSort = true, location = 0, distance = 100, threshold = 0.4, minMatchCharLength = 2, keys = ["title", "permalink", "summary", "content"] }

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "faq"
    name = "FAQ"
    url = "/faq/"
    weight = 20
  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 30
  [[menu.main]]
    identifier = "search"
    name = "🔍"
    url = "/search/"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
